.TH BEDKILL 1
.SH NAME
bedkill \- kill all BED processes running on frontends
.SH SYNOPSIS
.B bedkill
.SH DESCRIPTION
.I Bedkill
broadcasts a \f2kill\f1 message to all BED processes.  It is useful for
quickly stopping all BED processes.  This is very helpful when debugging
the distributed odt/download/upload software.
.SH "SEE ALSO"
bed(1), bedreboot(1)

